### ISSUE TITLE
ImportError: No module named resource

### ISSUE THREAD

**Issue by svlada** [progrium/ginkgo#74]
I have problem installing ginkgo. When I run setup.py following exception occurs.

C:\git\ginkgo>python setup.py install
Traceback (most recent call last):
  File "setup.py", line 5, in <module>
    from ginkgo import **version**
  File "C:\git\ginkgo\ginkgo__init__.py", line 25, in <module>
    from .core import Service
  File "C:\git\ginkgo\ginkgo\core.py", line 19, in <module>
    from .util import AbstractStateMachine
  File "C:\git\ginkgo\ginkgo\util.py", line 7, in <module>
    import resource
ImportError: No module named resource

**Comment by progrium** [comment]
Thanks for the report. Do you have setuptools installed?

**Comment by svlada** [comment]
Yes I have installed latest setup tools.

**Comment by erikalfthan** [comment]
Really old issue, but if any one else is looking into ginkgo, I guess I can post my findings ...

I ran in to the same problem when trying to install on Windows. resource is a unix only (native) module according to python documentation.
